spring.application.name=demo

jwt.secret=${JWT_SECRET:superSecretKey12345!@#$}
jwt.access-expiration-ms=${JWT_ACCESS_EXPIRATION_MS:1800000}
jwt.refresh-expiration-ms=${JWT_REFRESH_EXPIRATION_MS:604800000}
